"""Centralized default values used across configuration and runtime components."""

DEFAULT_GA_LOCAL_SEARCH_MAX_ITERATIONS = 100
DEFAULT_GA_CLONE_DELTA = 1.0
DEFAULT_GA_STAGNATION_PERIOD = 10
DEFAULT_GA_STAGNATION_FTOL = 1e-6
DEFAULT_GA_TIME_LIMIT = "00:05:00"

DEFAULT_SIMULATION_REROUTE_DEGRADATION_THRESHOLD = 1.20
DEFAULT_SIMULATION_CLUSTER_DEGRADATION_THRESHOLD = 1.05
DEFAULT_SIMULATION_PENALTY_OVERCAPACITY_PER_UNIT = 100000.0
DEFAULT_SIMULATION_PENALTY_OVERTIME_PER_MINUTE = 50000.0
